# Generated by 'click-buildtool elem2make' on Mon May 13 15:21:51 IST 2019
ELEMENT_OBJS__0 = \
adjusttimestamp.o \
aggcounter.o \
aggpktcounter.o \
aggregatefilter.o \
aggregatefirst.o \
aggregateip.o \
aggregateipaddrpair.o \
aggregateipflows.o \
aggregatelast.o \
aggregatelen.o \
aggregatenotifier.o \
aggregatepaint.o \
anonipaddr.o \
eraseippayload.o \
fromcapdump.o \
fromdagdump.o \
fromipsumdump.o \
fromnetflowsumdump.o \
fromnlanrdump.o \
fromtcpdump.o \
ipsumdump_anno.o \
ipsumdump_icmp.o \
ipsumdump_ip.o \
ipsumdump_link.o \
ipsumdump_payload.o \
ipsumdump_tcp.o \
ipsumdump_udp.o \
ipsumdumpinfo.o \
settimestampdelta.o \
storetimestamp.o \
storeudptimeseqrecord.o \
timefilter.o \
timerange.o \
timesortedsched.o \
timestampaccum.o \
toipflowdumps.o \
toipsumdump.o \

ELEMENT_OBJS__1 = \
ftpportmapper.o \

ELEMENT_OBJS__2 = \
adaptivered.o \
codel.o \
red.o \

ELEMENT_OBJS__3 = \
arpfaker.o \
arpprint.o \
arpquerier.o \
arpresponder.o \
arptable.o \
checkarpheader.o \
ensureether.o \
etherencap.o \
ethermirror.o \
etherpausesource.o \
etherrewrite.o \
ethervlanencap.o \
getetheraddress.o \
hostetherfilter.o \
setetheraddress.o \
setvlananno.o \
storeetheraddress.o \
stripethervlanheader.o \
vlandecap.o \
vlanencap.o \

ELEMENT_OBJS__4 = \
checkicmpheader.o \
icmperror.o \
icmpipencap.o \
icmppingencap.o \
icmppingresponder.o \
icmppingrewriter.o \
icmprewriter.o \
icmpsendpings.o \

ELEMENT_OBJS__5 = \
checkipheader.o \
checkipheader2.o \
decipttl.o \
directiplookup.o \
fixipsrc.o \
getipaddress.o \
ipaddrpairrewriter.o \
ipaddrrewriter.o \
ipclassifier.o \
ipencap.o \
ipfieldinfo.o \
ipfilter.o \
ipfragmenter.o \
ipgwoptions.o \
ipinputcombo.o \
ipmirror.o \
ipnameinfo.o \
ipoutputcombo.o \
ipprint.o \
ipratemon.o \
ipreassembler.o \
iprewriterbase.o \
iproutetable.o \
iprwmapping.o \
iprwpattern.o \
iprwpatterns.o \
lineariplookup.o \
lookupiproute.o \
lookupiproutelinux.o \
lookupiproutemp.o \
markipce.o \
markipheader.o \
radixiplookup.o \
rangeiplookup.o \
rfc2507c.o \
rfc2507d.o \
ripsend.o \
rripmapper.o \
setipaddress.o \
setipchecksum.o \
setipdscp.o \
setipecn.o \
setrandipaddress.o \
siphmapper.o \
sortediplookup.o \
storeipaddress.o \
stripipheader.o \
truncateippayload.o \
unstripipheader.o \

ELEMENT_OBJS__6 = \
simpleidle.o \
simplepriosched.o \
simplepullswitch.o \
simplerrsched.o \

ELEMENT_OBJS__7 = \
align.o \
annotationinfo.o \
averagecounter.o \
bandwidthmeter.o \
bandwidthshaper.o \
block.o \
burster.o \
bwratedsplitter.o \
bwratedunqueue.o \
bypass.o \
checkcrc32.o \
checklength.o \
checkpaint.o \
classification.o \
classifier.o \
clickyinfo.o \
clipboard.o \
compblock.o \
counter.o \
cpuqueue.o \
cpuswitch.o \
delayshaper.o \
delayunqueue.o \
devirtualizeinfo.o \
discard.o \
discardnofree.o \
drivermanager.o \
dropbroadcasts.o \
drr.o \
flowinfo.o \
frontdropqueue.o \
fullnotequeue.o \
hashswitch.o \
hub.o \
idle.o \
infinitesource.o \
inputswitch.o \
linkunqueue.o \
markmacheader.o \
messageelement.o \
meter.o \
mixedqueue.o \
notifierqueue.o \
nullelement.o \
nulls.o \
pad.o \
paint.o \
paintswitch.o \
painttee.o \
print.o \
priosched.o \
pullswitch.o \
quicknotequeue.o \
quitwatcher.o \
randomerror.o \
randomsample.o \
randomsource.o \
randomswitch.o \
ratedsource.o \
ratedsplitter.o \
ratedunqueue.o \
resize.o \
rrsched.o \
rrswitch.o \
script.o \
setannobyte.o \
setcrc32.o \
setpackettype.o \
settimestamp.o \
shaper.o \
simplequeue.o \
staticpullswitch.o \
staticswitch.o \
storedata.o \
stridesched.o \
strideswitch.o \
strip.o \
striptonet.o \
suppressor.o \
switch.o \
tee.o \
threadsafequeue.o \
timedsink.o \
timedsource.o \
timedunqueue.o \
truncate.o \
unqueue.o \
unqueue2.o \
unstrip.o \

ELEMENT_OBJS__8 = \
checktcpheader.o \
checkudpheader.o \
dynudpipencap.o \
fasttcpflows.o \
fastudpflows.o \
iprewriter.o \
settcpchecksum.o \
setudpchecksum.o \
tcpfragmenter.o \
tcpipsend.o \
tcprewriter.o \
udpipencap.o \
udprewriter.o \

ELEMENT_OBJS__9 = \
bhmtest.o \
biginttest.o \
bitvectortest.o \
blockthread.o \
checkpacket.o \
clptest.o \
comparepackets.o \
confparsetest.o \
cryptotest.o \
dequetest.o \
errortest.o \
functiontest.o \
handlertask.o \
hashtabletest.o \
heaptest.o \
listtest.o \
mtdietest.o \
neighborhoodtest.o \
notifierdebug.o \
notifiertest.o \
nulltask.o \
packettest.o \
queueyanktest.o \
randomseed.o \
schedordertest.o \
sorttest.o \
taskthreadtest.o \
timertest.o \
tokenbuckettest.o \
upstreamnotifier.o \
vectortest.o \

ELEMENT_OBJS__10 = \
spinlockacquire.o \
spinlockinfo.o \
spinlockpush.o \
spinlockrelease.o \
staticthreadsched.o \

ELEMENT_OBJS__11 = \
changeuid.o \
chattersocket.o \
controlsocket.o \
fakepcap.o \
fastudpsrc.o \
fromdevice.o \
fromdump.o \
fromhost.o \
fromrawsocket.o \
fromsocket.o \
handlerproxy.o \
ipflowrawsockets.o \
kernelfilter.o \
kerneltap.o \
kerneltun.o \
khandlerproxy.o \
mcastsocket.o \
netmapinfo.o \
progressbar.o \
rawsocket.o \
socket.o \
todevice.o \
todump.o \
tohost.o \
torawsocket.o \
tosocket.o \
umlswitch.o \

ELEMENT_OBJS__12 = \
PrintSignalStrength.o \
athdescdecap.o \
athdescencap.o \
autoratefallback.o \
availablerates.o \
bitrate.o \
ethercount.o \
extradecap.o \
extraencap.o \
filterfailures.o \
filterphyerr.o \
filtertx.o \
fromhandler.o \
linktable.o \
madwifirate.o \
packetstore.o \
printtxfeedback.o \
printwifi.o \
prism2decap.o \
prism2encap.o \
probetxrate.o \
pushanno.o \
radiotapdecap.o \
radiotapencap.o \
rc4.o \
readanno.o \
rxstats.o \
setnoack.o \
setrts.o \
settxpower.o \
settxrate.o \
wepdecap.o \
wepencap.o \
wifidecap.o \
wifidefrag.o \
wifidupefilter.o \
wifiencap.o \
wififragment.o \
wifiseq.o \
wirelessinfo.o \

ELEMENT_OBJS__13 = \
associationresponder.o \
beaconsource.o \
openauthresponder.o \
proberesponder.o \
stationtable.o \

ELEMENT_OBJS__14 = \
associationrequester.o \
beaconscanner.o \
beacontracker.o \
openauthrequester.o \
proberequester.o \

ELEMENT_OBJS = \
$(ELEMENT_OBJS__0) \
$(ELEMENT_OBJS__1) \
$(ELEMENT_OBJS__2) \
$(ELEMENT_OBJS__3) \
$(ELEMENT_OBJS__4) \
$(ELEMENT_OBJS__5) \
$(ELEMENT_OBJS__6) \
$(ELEMENT_OBJS__7) \
$(ELEMENT_OBJS__8) \
$(ELEMENT_OBJS__9) \
$(ELEMENT_OBJS__10) \
$(ELEMENT_OBJS__11) \
$(ELEMENT_OBJS__12) \
$(ELEMENT_OBJS__13) \
$(ELEMENT_OBJS__14) \

$(ELEMENT_OBJS__0): %.o: ../elements/analysis/%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
$(patsubst %.o,%.s,$(ELEMENT_OBJS__0)): %.s: ../elements/analysis/%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)
$(patsubst %.o,%.ii,$(ELEMENT_OBJS__0)): %.ii: ../elements/analysis/%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)

$(ELEMENT_OBJS__1): %.o: ../elements/app/%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
$(patsubst %.o,%.ii,$(ELEMENT_OBJS__1)): %.ii: ../elements/app/%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)
$(patsubst %.o,%.s,$(ELEMENT_OBJS__1)): %.s: ../elements/app/%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)

$(ELEMENT_OBJS__2): %.o: ../elements/aqm/%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
$(patsubst %.o,%.s,$(ELEMENT_OBJS__2)): %.s: ../elements/aqm/%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)
$(patsubst %.o,%.ii,$(ELEMENT_OBJS__2)): %.ii: ../elements/aqm/%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)

$(ELEMENT_OBJS__3): %.o: ../elements/ethernet/%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
$(patsubst %.o,%.ii,$(ELEMENT_OBJS__3)): %.ii: ../elements/ethernet/%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)
$(patsubst %.o,%.s,$(ELEMENT_OBJS__3)): %.s: ../elements/ethernet/%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)

$(ELEMENT_OBJS__4): %.o: ../elements/icmp/%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
$(patsubst %.o,%.s,$(ELEMENT_OBJS__4)): %.s: ../elements/icmp/%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)
$(patsubst %.o,%.ii,$(ELEMENT_OBJS__4)): %.ii: ../elements/icmp/%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)

$(ELEMENT_OBJS__5): %.o: ../elements/ip/%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
$(patsubst %.o,%.ii,$(ELEMENT_OBJS__5)): %.ii: ../elements/ip/%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)
$(patsubst %.o,%.s,$(ELEMENT_OBJS__5)): %.s: ../elements/ip/%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)

$(ELEMENT_OBJS__6): %.o: ../elements/simple/%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
$(patsubst %.o,%.s,$(ELEMENT_OBJS__6)): %.s: ../elements/simple/%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)
$(patsubst %.o,%.ii,$(ELEMENT_OBJS__6)): %.ii: ../elements/simple/%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)

$(ELEMENT_OBJS__7): %.o: ../elements/standard/%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
$(patsubst %.o,%.ii,$(ELEMENT_OBJS__7)): %.ii: ../elements/standard/%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)
$(patsubst %.o,%.s,$(ELEMENT_OBJS__7)): %.s: ../elements/standard/%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)

$(ELEMENT_OBJS__8): %.o: ../elements/tcpudp/%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
$(patsubst %.o,%.s,$(ELEMENT_OBJS__8)): %.s: ../elements/tcpudp/%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)
$(patsubst %.o,%.ii,$(ELEMENT_OBJS__8)): %.ii: ../elements/tcpudp/%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)

$(ELEMENT_OBJS__9): %.o: ../elements/test/%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
$(patsubst %.o,%.ii,$(ELEMENT_OBJS__9)): %.ii: ../elements/test/%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)
$(patsubst %.o,%.s,$(ELEMENT_OBJS__9)): %.s: ../elements/test/%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)

$(ELEMENT_OBJS__10): %.o: ../elements/threads/%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
$(patsubst %.o,%.s,$(ELEMENT_OBJS__10)): %.s: ../elements/threads/%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)
$(patsubst %.o,%.ii,$(ELEMENT_OBJS__10)): %.ii: ../elements/threads/%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)

$(ELEMENT_OBJS__11): %.o: ../elements/userlevel/%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
$(patsubst %.o,%.ii,$(ELEMENT_OBJS__11)): %.ii: ../elements/userlevel/%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)
$(patsubst %.o,%.s,$(ELEMENT_OBJS__11)): %.s: ../elements/userlevel/%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)

$(ELEMENT_OBJS__12): %.o: ../elements/wifi/%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
$(patsubst %.o,%.s,$(ELEMENT_OBJS__12)): %.s: ../elements/wifi/%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)
$(patsubst %.o,%.ii,$(ELEMENT_OBJS__12)): %.ii: ../elements/wifi/%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)

$(ELEMENT_OBJS__13): %.o: ../elements/wifi/ap/%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
$(patsubst %.o,%.ii,$(ELEMENT_OBJS__13)): %.ii: ../elements/wifi/ap/%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)
$(patsubst %.o,%.s,$(ELEMENT_OBJS__13)): %.s: ../elements/wifi/ap/%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)

$(ELEMENT_OBJS__14): %.o: ../elements/wifi/station/%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
$(patsubst %.o,%.s,$(ELEMENT_OBJS__14)): %.s: ../elements/wifi/station/%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)
$(patsubst %.o,%.ii,$(ELEMENT_OBJS__14)): %.ii: ../elements/wifi/station/%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)

